apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hanna-bot
spec:
  selector:
    matchLabels:
      app: hanna-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: hanna-bot
    spec:
      containers:
        - image: 191518685251.dkr.ecr.us-west-1.amazonaws.com/hanna-bot:latest
          imagePullPolicy: Always
          name: hanna-bot
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hanna-bot-service
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: hanna-bot
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: hanna-bot-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-1:191518685251:certificate/7e4e641f-01f7-4186-94fc-c7023548c092
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: hanna-bot-service
                port:
                  number: 80
